services:
  collaboration:
    build:
      context: ./collaboration
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 1234:1234
    environment:
      - PORT=1234

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 8080:8080
    environment:
      - COLLABORATION_URL=ws://collaboration:1234
      - PORT=8080
    depends_on:
      - collaboration

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 80:80
    depends_on:
      - api-gateway
      - collaboration
