apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: websocket-sample-api-gateway
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    # metadata:
    #   annotations:
    #     run.googleapis.com/vpc-access-egress: all-traffic
    #     run.googleapis.com/network-interfaces: '[{"network":"websocket-sample-vpc","subnetwork":"websocket-sample-subnet"}]'
    spec:
      # serviceAccountName: websocket-sample-api-gateway@velvety-glazing-420809.iam.gserviceaccount.com
      containers:
        - image: us-central1-docker.pkg.dev/velvety-glazing-420809/websocket-sample-repo/websocket-sample-api-gateway:latest
          env:
            - name: COLLABORATION_URL
              value: ws://websocket-sample-collaboration-641862643887.us-central1.run.app
