apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: websocket-sample-frontend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/velvety-glazing-420809/websocket-sample-repo/websocket-sample-frontend:latest
          ports:
            - containerPort: 80
